name: Package deliverables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: sudo apt-get install texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

    - name: Compile LaTeX document
      run: pdflatex -interaction=nonstopmode -halt-on-error Main.tex

    - name: Rename PDF
      run: mv Main.pdf ${{ secrets.STUDENT_NUMBER }}_report.pdf

    - name: Rename C++ file
      run: mv QuickSort.cpp ${{ secrets.STUDENT_NUMBER }}_quicksort.cpp

    - name: Zip the files
      run: zip release.zip ${{ secrets.STUDENT_NUMBER }}_report.pdf ${{ secrets.STUDENT_NUMBER }}_quicksort.cpp

    - name: Upload Zip as artifact
      uses: actions/upload-artifact@v2
      with:
        name: compiled-release
        path: release.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download compiled release artifact
        uses: actions/download-artifact@v3
        with:
          name: compiled-release

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
